# Generated by Django 4.0.3 on 2022-03-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='upload')),
                ('mini_description', models.CharField(max_length=300)),
                ('status', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='upload')),
                ('mini_description', models.CharField(max_length=300)),
                ('status', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='upload')),
                ('date', models.DateTimeField(blank=True)),
                ('view', models.IntegerField(blank=True, default=0)),
                ('comment', models.TextField(blank=True)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('rating', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('status', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='upload')),
                ('status', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('facebook', models.CharField(max_length=300)),
                ('twitter', models.CharField(max_length=300)),
                ('pinterest', models.CharField(max_length=300)),
                ('instagram', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='upload')),
                ('status', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
